apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: KFConfig
spec:
  features:
    - name: PubSub.Routing
      enabled: true
  tracing:
    samplingRate: "1"
    stdout: true
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"
    otel:
      endpointAddress: "localhost:4317"
      isSecure: false
      protocol: grpc 
  logging:
    apiLogging:
      enabled: true
      obfuscateURLs: true
      omitHealthChecks: true
  metrics:
    enabled: true