apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cpubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: 'amqp://guest:guest@localhost:5672'
  - name: durable
    value: 'true'
  # - name: autoAck
  #   value: 'false'
  # - name: exchange
  #   value: 'amq.topic'
  # - name: queue
  #   value: 'dapr'
  # - name: routingKey
  #   value: 'dapr'
  # - name: maxInflight
  #   value: '1'