apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfiamsvc-deployment
  namespace: kfiamservice  # Specify the namespace
  labels:
    app: kfiamsvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kfiamsvc
  template:
    metadata:
      labels:
        app: kfiamsvc
      annotations:
        dapr.io/enabled: "true"  # Enable Dapr
        dapr.io/app-id: "kfiamsvc"  # Unique Dapr app ID
        dapr.io/app-port: "8081"  # Application port for Dapr sidecar
    spec:
      containers:
      - name: kfiamsvc-container
        image: thedineshbabukf/kfiamsvc:latest  # Replace with your Docker Hub image
        ports:
        - containerPort: 8081  # Application port inside the container
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: kfiamsvc-service
  namespace: kfiamservice  # Specify the namespace
  labels:
    app: kfiamsvc
spec:
  type: LoadBalancer
  ports:
    - port: 80  # Exposed port to external users
      targetPort: 8081  # Port inside the container
  selector:
    app: kfiamsvc
