apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: secondconsumersubscriptions
  namespace: default
spec:
  pubsubname: 2cpubsub
  topic: kfone
  routes:
    rules:
      - match: "event.type == 'employee'"
        path: employees