# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy the HTML file into the Nginx image
COPY ./index.html /usr/share/nginx/html/index.html

# Expose port 80 for the Nginx web server
EXPOSE 80
