apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: firstconsumersubscriptions
  namespace: default
spec:
  pubsubname: cpubsub
  topic: kfone
  routes:
    rules:
      - match: "event.type == 'organization'"
        path: organizations
      - match: "event.type == 'employee'"
        path: employees
    # default: products