apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: kf-resiliency
scopes:
  - kf-advance-service

spec:
  policies:
    retries:
      retryForever:
        policy: constant
        duration: 5s
        maxRetries: -1 

    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 5s 
        trip: consecutiveFailures >= 5

  targets:
    apps:
      kf-iam-service:
        retry: retryForever
        circuitBreaker: simpleCB