apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: kfadvanceserviceSubscriptions
  namespace: default
spec:
  pubsubname: kf-pubsub
  topic: kfone
  routes:
    rules:
      - match: "event.type == 'createOrganization'"
        path: createOrganization
      # - match: "event.type == 'createEmployee'"
      #   path: createEmployee
    # default: products