apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: kfadvanceserviceConfig
spec:
  features:
    - name: PubSub.Routing
      enabled: true
  tracing:
    samplingRate: "1"
    stdout: true
    otel:
      endpointAddress: "localhost:4317"
      isSecure: false
      protocol: grpc 