### Create an Organization
POST http://localhost:59840/createorganization
Content-Type: application/json

{
  "name": "ORG001",
  "description": "organization 001",
  "domain": "org.com",
  "logo": "string"
}

### Create an Employee
POST http://localhost:59840/createemployee
Content-Type: application/json

{
  "name": "EMP 1",
  "email": "emp@xyz.com",
  "password": "***",
  "organizationId": "001",
  "role": "admin"
}

### Call IAM Service From KF Advance Service

GET http://localhost:3320/invokeservice1
Content-Type: application/json

### Get Secret From KF Insights Service

GET http://localhost:3320/secret
Content-Type: application/json

### Get Secret From KF IAM Service

GET http://localhost:3310/secret
Content-Type: application/json

